### ISSUE TITLE
Issue with uploading profile image

### ISSUE THREAD

**Issue by shannontreadway** [sgfdevs/sgf.dev#14]
I am trying to upload a profile pic to my account, and am getting an error.  I am using Chrome version 90.0.4430.93.  Attached is the original image I tried to upload as well as a screenshot of the browser console after I got the error.

![headshotForAccounts](https://user-images.githubusercontent.com/71666248/117354265-c1755c00-ae76-11eb-83c2-e0396251bace.jpg)

![uploadErrors](https://user-images.githubusercontent.com/71666248/117353721-18c6fc80-ae76-11eb-991a-99d5793d1621.jpg)

**Comment by mykebates** [comment]
This no longer seems to be a replicable issue. @shannontreadway confirmed the exact same image uploads fine now. Will keep an eye out for this issue in the future.
